workflows:
  flutter-android-build:
    name: Flutter Android Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk